### Create Employee
@baseUrl = http://localhost:8080
@username = user
@password = 71e74bce-1d0e-4fa5-b0eb-e78723eb36e3

POST {{baseUrl}}/employees
Content-Type: application/json
//Authorization: Basic {{username}} {{password}}

{
  "name": "Virginia Fonseca",
  "email": "virginia.fonseca@company.com"
}
