### Create Employee
@baseUrl = http://localhost:8080

POST {{baseUrl}}/employees
Content-Type: application/json

{
  "name": "João Silva",
  "email": "joao.silva@company.com",
  "role": {
    "id": 3
  }
}

