### Update Employee
@baseUrl = http://localhost:8080
@employeeId = 1
@username = user
@password = paste_password_here

PUT {{baseUrl}}/employees/{{employeeId}}
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

{
  "name": "Ana Silva Updated",
  "email": "ana.silva.updated@company.com",
  "role": {
    "id": 2
  },
  "createdAt": "2026-05-30T10:00:00Z"
}
