### Create Employee
@baseUrl = http://localhost:8080

POST {{baseUrl}}/employees
Content-Type: application/json

{
  "name": "Ana Silva",
  "email": "ana.silva@company.com",
  "role": {
    "id": 1
  },
  "createdAt": "2026-05-30T10:00:00Z"
}

